/*
 * message strings
 * from original maps files
 */

#include "gamedefs.h"

#ifdef MAPS_MESSAGES

const char* maps_messages[] = {
_("Beltway"),
_("A balanced scenario with lots of resources and land to explore."),
_("Whiteshield"),
_("Sorpigal"),
_("Middle Gate"),
_("Dragadune"),
_("Whittingham"),
_("Winterkill"),
_("Blacksford"),
_("Viper's Nest"),
_("Wildabar"),
_("Pinehurst"),
_("Alamar"),
_("Weddington"),
_("Atlantium"),
_("Beware the edge of the world!"),
_("Look out!"),
_("Congratulations! After navigating the treacherous coast, you have established trade between the north and south."),
_("mirror"),
_("a mirror"),
_("What turns everything around but does not move?"),
_("Reinforcements have arrived, Gold from the homelands!"),
_("You found something!"),
_("You found something!"),
_("Beware the moors and stick to the roads."),
_("Beware the moors and stick to the roads."),
_("Beware the moors and stick to the roads."),
_("Broken Alliance"),
_("The alliance has crumbled and all are at war. Lots of resources but little time to prepare."),
_("Xabran"),
_("Willow"),
_("Sheltemburg"),
_("Corackston"),
_("Vertigo"),
_("Peacekeeper"),
_("Woodhaven"),
_("Hillstone"),
_("Whiteshield"),
_("Bloodreign"),
_("Dragontooth"),
_("The wizard has an island in the southeast."),
_("The center island is rumored to harbor great spells."),
_("Watch out for Purple!"),
_("Avone"),
_("Because the Darkscale Valley is so barren, the Emperor will be sending wood to you every week. Use it wisely, for it is all you shall have."),
_("The wood has arrived."),
_("Chandler"),
_("South Mill"),
_("Roc Haven"),
_("Like, Stuff And Junk?"),
_("Timberhill"),
_("Fenton"),
_("Pixie"),
_("nbury"),
_("Mr. Yellow's Income"),
_("Red's Rubles"),
_("Green's Groceries"),
_("Glastonbury"),
_("Pinehurst"),
_("Woodhaven"),
_("Hillstone"),
_("Black Vein"),
_("The first piece of the artifact now lies in the hands of the Unholy Order of Warlocks. You must annihilate them, and their allies to the north. They will surely give us what we seek in exchange for their feeble lives."),
_("Welcome to Windfall Island!"),
_("Alamar"),
_("Sorpigal"),
_("New Dawn"),
_("Erliquin"),
_("Stuff for red"),
_("South Mill"),
_("Green's Groceries"),
_("Avalon"),
_("Brownston"),
_("This area must be secured for the sake of the Empire. Our spies have reported a discord between The kingdom of the knights to the north, and that of the oppressive sorceresses to the northeast. Perhaps this feud can be exploited for our gain..."),
_("An old elf is sitting on a rock in a glen, pounding on the shackles on his feet with a stone. You help him remove them and ask him his tale. \"I'm a deserter from Drakonia's army. She has enslaved all the elves to support her madness. She must be stopped.\" Then he slips into the woods without a sound, leaving behind just his cloak."),
_("Drakonia"),
_("As you enter the small clearing, you see a familiar figure talking to a group of halflings and soldiers. You stay awhile and listen to his speech. \"The time to throw off these chains of tyranny is now! We must strike at the heart of her empire, and destroy the evil that she has brought to our land.\" As the old elf finishes speaking, he gets up from his mossy seat and once again, blends into the woods with incredible grace."),
_("As you approach the barrier, you see the old elf you helped free. This time, however, you see that he is wearing a cape of fine weave, and a wooden crown is on his head. He sees your forces, and says \"Take this sword, and with it, strike down Drakonia and help free my people.\" The old elf then strides regally into the woods."),
_("You cautiously ride through the trees, looking out for enemy assaults, when suddenly, the old elf is beside you. \"Your quest is almost at an end, my friend. All that remains is for you to lay seige to these last few castles. The fate of my people rests upon your final battles here. May the gods be with you as well.\"  He turns to leave, but you ask him his name before he is gone. Over his shoulder, as he is leaving he says \"I am Ilthanis, king of the elves.\""),
_("No Description"),
_("Middletown"),
_("Scummy"),
_("Scabsdale"),
_("The way of might"),
_("The way of magic"),
_("The way of numbers"),
_("No stuff for red"),
_("Willow"),
_("lfie"),
_("Sheltemburg"),
_("Corackston"),
_("Blackridge"),
_("Pinehurst"),
_("Alamar"),
_("Blackfang"),
_("Raste"),
_("MONEY, MONEY, MONEY!"),
_("Our spies have discovered that the barbarian hordes are now receiving support from kraeger! You must hurry and find the third piece before your forces here are crushed!"),
_("Yellow's Steady Cash"),
_("Tchudes"),
_("Fadlan"),
_("Weed Patch"),
_("Roc Haven"),
_("Red's Connection"),
_("The third piece of the artifact is somewhere to the north, that much we know. We are still unsure of its exact location, but our spies are out gathering information. The forces in this area are too strong to be completely subjugated, so take what you can and hold on to it tightly."),
_("We have just learned that the artifact is on an island north of this continent. However, there does not appear to be any means to get there. Stay very alert for any possible way across the narrow channel."),
_("Paper can gain you what wood and sail cannot."),
_("Windfall Isle"),
_("Island of the Elves"),
_("Blackfang"),
_("Basenji"),
_("Algary"),
_("Sorpigal"),
_("These lands are beholden to Lord Kraeger."),
_("As you make  your way through the last of the golemn debris, a group of halflings runs towards you carrying fruit and flowers. \"Thank you so much!\" Their leader exclaims, \"We've been trapped in here for ever! Come by our homes, we'll pack up and go with you!\""),
_("In this glen live some very naughty halflings. Stay Away!"),
_("Hampshire"),
_("Chilton"),
_("Lord Kreager"),
_("Income for Yellow."),
_("Roc Haven"),
_("Regrettably, you have no castle with which to begin your assault. Fortunately, however, Kraeger's forces are weak here in the south, and you have bribed a rebel necromancer to aid you in the beginning of your conquest."),
_("Green's Groceries"),
_("No sulfer fer Yella."),
_("Antioch"),
_("No Description"),
_("Meramec"),
_("Quick Silver"),
_("Westmoor"),
_("Greenroot"),
_("Sheltemburg"),
_("Pinehurst"),
_("Whiteshield"),
_("Dragontooth"),
_("Greywind"),
_("Portsmith"),
_("Vulcania"),
_("Fountainhead"),
_("Green's Groceries"),
_("I am one of the few remaining survivors of the wrecked pleasure ship, Exhorbitance. I think we'll all be dead of hunger soon, for we are out of caviar. We ate the chef yesterday."),
_("Dead Pine"),
_("Rotten Birch"),
_("Black Oak"),
_("Fetid Elm"),
_("Valley Of The Damned"),
_("Money For Red"),
_("Wormed Ash"),
_("Stuff for Yellow"),
_("As you make your way to the shrine, some very thin and hollow-eyed men come out of the flower patch and stare at you.  Seeing that you want the gold, one of them says to you \"Hey, man, if you're, like, so lusty for earthly wealth, then, like, have this too.\" You graciously take what they have offered and back out of the clearing."),
_("You must, like, forsake your earthly wealth and, like, join us on the island of the lotus eaters."),
_("Beware the sirens!"),
_("Ibn Fadlan"),
_("This land and all others are now under the sole ownership of Ibn Fadlan, the Undead King. Any disregard for his magesty's soverign rule is to be punished by death most horrendous."),
_("Algary"),
_("Sorpigal"),
_("New Dawn"),
_("Erliquin"),
_("Avone"),
_("Unite the Tribes. Don't lose your main hero, the first Descendant."),
_("Westmoor"),
_("Garamok"),
_("Corackston"),
_("Blackridge"),
_("Jarkonas"),
_("Pinehurst"),
_("Your rival, the kingdom of Harondale, is attacking your weak border towns! Recover from their first strike and crush them completely."),
_("Weed Patch"),
_("Roc Haven"),
_("Avalon"),
_("Trilobar"),
_("Stronghold"),
_("Find Your Wayward Son who is rumored to be living in the desolate lands. Do it within 8 weeks or it will be of no help to your family."),
_("IslandHome"),
_("Obsidian"),
_("Rogar"),
_("Dragontooth"),
_("Lavalor"),
_("Vaultius"),
_("Searching in the dust of this abandoned campsite, you find a magic scroll."),
_("This village is in extremely poor shape. There is no chance of getting more than some of the lesser creatures here."),
_("This village appears to be in little better shape than the first one you saw. As you approach the village an old man hands you a slip of paper, with the following message, \"Joseph lives in the town of IslandHome.\""),
_("This rundown village looks like it was once the epicenter of an enormous, but now ruined, city. Under a pile of rubble you find an object which looks like it has lain there for ages."),
_("Compared to the rest of the villages in this land, this village seems grand, but in any other land it would seem poor. From here you can see the tall spires of the Warlock's tower of Dragons."),
_("These lands are desolate and for the most part devoid of resources. Not even the bravest heroes dare to venture into them, and plants are rare and precious here. Who knows what else awaits?"),
_("Many dust plumes rise from the floor of this small valley. You see various bands of nomads roaming about, and in the distant, the bright flames of their camp."),
_("As you approach the tent, the leader of the nomads comes out to greet you. He says, \"It was prophecied many years ago that a great hero would come to greet us in our sacred valley, and we would prosper afterwords. Now it has come to pass, and we offer you these gifts as tokens of our thanks.\""),
_("Dark clouds loom overhead as you enter this valley."),
_("You send this letter back to the king,\"A month has passed and we have not discovered the wizard Joseph. I only hope that we are able to locate him in time to aid us in our struggle.\""),
_("Only a month remains in which to find Joseph."),
_("In two more weeks, if you have not located Joseph, your kingdom will surely lose its current battle with Harondale."),
_("This is the last week you have to find the rebel wizard Joseph! Good Luck in your quest."),
_("Rescue your crazy Uncle Ivan. Find him within 4 months or it will be no help to your kingdom."),
_("Ivan lives in the desert."),
_("Borderlands"),
_("IvanHome"),
_("Gungtooth"),
_("There are remnants of a mighty battle fought here, not too long ago. It looks as if whoever came this way may have made this their final stop."),
_("One of your scouts reports a tiny cave nearby. Upon investigating, you discover a small cache of goods. In the dirt by them is etched 'Ivan'."),
_("Snagged on a thorny bush, you discover a scrap of cloth. The design on it looks like the coat of arms of Ivan's house!"),
_("Someone notices a piece of parchment lying behind a clump of grass. You pick it up. It looks to be a page from a journal, and it reads, \"...made it past the first guardians. Hopefully will reach the ancient desert city soon. Only hope my forces are strong enough to survive...\""),
_("You notice some runes hastily scrawled into a rock by your feet, They look like the initials of Uncle Ivan!"),
_("As you approach,  you hear whispered mentions of \"the wild barbarian who passed this way months before\". One of the villagers approaches you and hands you an object, saying \"The wild one dropped this. You must be his kin. Therefore I give it to you. But beware! Many in the village will not be as friendly as I.\""),
_("Your advance scouts come riding back to you with the following news. They believe they have found signs that Uncle Ivan was in this general area, and that he made his way to the north many months ago. Also they say there is a town nearby and many resources to the east."),
_("Gorgomar"),
_("Destroy the Barbarians who are attacking the southern border of your kingdom! Recover your towns and then invade the jungle kingdom."),
_("Avone"),
_("Drakoran"),
_("Weed Patch"),
_("Brownston"),
_("The castle of Drakonran in the east has been taken by the barbarians! Two other towns to the west have also been taken, but the barbarian armies were fairly decimated in the process."),
_("Jungomar"),
_("The Valley of Aruk."),
_("Woodville"),
_("The Eastern Town."),
_("The cities of the plains."),
_("The western town."),
_("Hilltop"),
_("Yorksford"),
_("Sherman"),
_("Roscomon"),
_("Elk's Head"),
_("Pig's Eye"),
_("Yellow gets some stuff"),
_("Blacksford"),
_("Burton"),
_("Green gets stuff"),
_("Red stuff"),
_("Redshield"),
_("Retake the Castle of Ivory Gates."),
_("Ivory Gates"),
_("Barrowton"),
_("South Mill"),
_("Avalon"),
_("Antioch"),
_("Brownston"),
_("Whittingham"),
_("Westfork"),
_("Hilltop"),
_("Gain the aid of the elves. They will not allow trees to be chopped down, so we will send you wood every 2 weeks. You have 7 months!"),
_("Middleton"),
_("TreeHome"),
_("A shipment of wood has arrived from your kingdom!"),
_("The writing on this sign is too faded to read."),
_("You notice that mines and resources in the elvish lands are few, and you send word to your kingdom that you will need extra supplies. They should respond within a fortnight."),
_("You have recieved a shipment of supplies from your kingdom! There is a note attached, \"These are all we could afford to send you from our treasuries, as the war with Harondale is taxing us greatly. We will send more in two weeks.\""),
_("You have recieved a shipment of supplies from your kingdom!"),
_("The diplomats who were sent here ahead of you report that the elves will only cooperate with you if you will recover the golden bow for them. It was stolen by their enemies, the Dragons and hidden behind magic barriers."),
_("Edgewood"),
_("You hear melodic strains of elvish music as you enter this clearing."),
_("A great Black dragon stands before you. It speaks in a suprisingly soft voice, saying, \"The elves believe they have sent another hero to reclaim their prize. I believe they have sent me another meal.\""),
_("Elowyn"),
_("Gallavant"),
_("Other than the dragons, the elves don't have any enemies."),
_("No one has ever made it out of the deadly swamps alive!"),
_("Some unlucky adventurers have been captured and imprisoned in these lands."),
_("Beware the whiporwill..."),
_("Beware the deadly swamps!"),
_("Sorpigal"),
_("New Dawn"),
_("The Epic battle against Your Rival! Eliminate everything! Total Warfare! Don't Lose your first hero!"),
_("Wood's Lord"),
_("Pig's Eye"),
_("Blacksford"),
_("Burton"),
_("Blackburn"),
_("Lankershire"),
_("Jarkonas VI"),
_("Green stuff"),
_("Red stuff"),
_("Tundara"),
_("Vulcania"),
_("Sansobar"),
_("Atlantium"),
_("Baywatch"),
_("Wildabar"),
_("Fountainhead"),
_("Vertigo"),
_("Winterkill"),
_("Sandcaster"),
_("Green bonus stuff"),
_("Red bonus"),
_("Wizards 1"),
_("No Description"),
_("Sorpigal"),
_("New Dawn"),
_("Hilltown"),
_("Roc Haven"),
_("Avalon"),
_("Brownston"),
_("Whittingham"),
_("Snowdrop"),
_("Island of Wolcott"),
_("Yorksford"),
_("Elk's Head"),
_("Uncle Leo"),
_("Seek the great library, for only with the guidance of the musty tomes therin will you find the means to reveal and bind the fount to your will."),
_("Farlien"),
_("Vertigo"),
_("The Emerald Isle"),
_("Blackfang"),
_("Algary"),
_("Sorpigal"),
_("Erliquin"),
_("Big Oak"),
_("Those who seek knowledge are welcome to the city of Chronos."),
_("Chronos"),
_("Chandler"),
_("South Mill"),
_("The Kingly Wastes"),
_("Red's Lunch Money"),
_("Green's Allowance"),
_("Stuff For Yellow"),
_("Joseph"),
_("You bribe the entrance guards of this dingy prison camp. They agree to look the other way for a little while."),
_("One of the seers in your castle comes to you in the morning with urgent news. Your one time comrade, the wizard Joseph, and his armies have been imprisoned in a jail nearby. His power would surely aid you in your quest to reclaim the library, you think to yourself. Perhaps there is a way to rescue him..."),
_("One of your aides reports that the Castle of Farlien is located on the northeast spur of this island, and is a stronghold for the enemy. He urges you to take it out as soon as possible, and then move onto other islands."),
_("High in the snowy crags, you meet an old witch who, in return for a trinket of yours, gives you a powerful magical object she used to use as a footstool before she was exiled into the mountains by her own townspeople."),
_("Hillstone"),
_("Whiteshield"),
_("Bloodreign"),
_("Dragontooth"),
_("Greywind"),
_("The convoy has at long last arrived. Regretably, it has been beset by bandits on its journey here, and has far less supplies than we had hoped. Make your way south, for our spies have found rich mines there."),
_("The convoy should have been here by now! Let us hope that it is safe and still on its way."),
_("Before questing for the orb of negation, you must first crush the local opposition. After the Sorceresses are removed from the earth, go east where legend says the orb lies.  You may expect a convoy of supplies in a week or so to aid your conquest."),
_("Atlantium"),
_("Wildabar"),
_("Evil Igor"),
_("No Description"),
_("Subbaculcha"),
_("Uncle Ivan"),
_("Green's Groceries"),
_("Red's Rubles"),
_("You have hired a barbarian of great power to aid you in this, your last quest. His origins are unknown to you, but you sense strong nobility beneath the furs and dirt that cover him. In addition, the famous explorer, Marco the wizard, is rumored to have wrecked his ship in this new land. Finding him would prove to be a much needed boon to your cause."),
_("Whittingham"),
_("Westfork"),
_("Hilltop"),
_("Sherman"),
_("Roscomon"),
_("Elk's Head"),
_("Viper's Nest"),
_("Pig's Eye"),
_("Burton"),
_("Lankershire"),
_("Fenton"),
_("Troy"),
_("Forder Oaks"),
_("Meramec"),
_("Quick Silver"),
_("You see an old mystic perched on a rock. You walk towards him to see if he has any words for you on your quest, and he says \"First I see you as a great conquerer of the lands of men. Secondly, I see you as a mighty ruler of vast armies, well loved by your troops. Thirdly, I see you as a slayer of legions of dragons, your body bathed in their fire. Lastly, I see you standing on the shores of the fount, unable to cross.\" Then the Mystic fades away."),
_("You see an old man bringing water towards the stables. Recognizing him as the mystic, you attempt to thank him for his gift with some gold. He refuses, but says to you instead, \"There are riddles guarding the source of the fount's power, and the dragons know the answers. Make your way through their lair, and you shall know victory.\""),
_("Arm of the Phoenix"),
_("Arm of the Cyclops"),
_("Arm of the Titan"),
_("Arm of the Crusader"),
_("Arm of the Dragon"),
_("Island of the meek"),
_("Yellow's Yarbols"),
_("Please...."),
_("Come and...."),
_("Help me...."),
_("I am...."),
_("Being held...."),
_("Prisoner on...."),
_("The island...."),
_("Of the necromancers...."),
_("You're almost there!"),
_("A little bit closer..."),
_("You're here! Oh, thank you thank you thank you! I'm in the jail east of the castle. Please hurry!"),
_("Notice- Those who put messages in bottles will be tortured."),
_("Welcome to the Spiral Isles"),
_("Go away!"),
_("You see a family of refugees making their way from the beach. You ask them about their plight and they tell you that they are from a once great city called Moss Side. They tell you that the castle was destroyed in a great conflagration, and they fled for fear of their lives."),
_("If you value your lives, for God's sake, Don't go through this whirlpool!"),
_("You've been warned!"),
_("This land has been claimed by the nation of Neroli. Interlopers are UNWELCOME."),
_("No gems, crystal, or mercury for red."),
_("Bloodreign"),
_("Marco"),
_("Dragontooth"),
_("Capture the town on the island off the southeast shore in order to construct a boat and travel back towards the mainland."),
_("Welcome to the sandy Isle."),
_("Gallavant"),
_("You have washed up on the beach after being shipwrecked. Your goal is to find a way home."),
_("Chandler"),
_("South Mill"),
_("Land's Edge"),
_("Find and defeat the Pirate Leader!"),
_("Waystop"),
_("Gallavant"),
_("Pinehurst"),
_("Woodhaven"),
_("Hillstone"),
_("Whiteshield"),
_("Dragontooth"),
_("Greywind"),
_("Pirate Cove"),
_("Middle Gate"),
_("The note in this bottle has become mostly indecipherable. All you can make out are references to deadly pirates, and hidden gold mines."),
_("This bottle is empty."),
_("You find a note in the bottle! It reads, \"My ship has been wrecked by the notorious pirates in this area! I am stranded on a small and barren island. Please, I beg you to come and rescue me!\""),
_("Welcome to the Sandbar."),
_("Beware of Pirates!"),
_("DirtWater"),
_("Martine"),
_("A man appears from behind the sand dune. \"At last,\" he says, \"Someone has come to rescue me! I am forever grateful. Alas all I have to offer you in return are these souvenirs from my wrecked ship.\""),
_("The Isle of Armoria"),
_("You hear a rumor from a peasant who lives in the town of Waystop. He says, \"The pirates control most of the sulfur mines in this area. They use it for the cannons on their bigger boats. If you want a mine, you'll have to defeat them.\""),
_("You are fighting on the side of your king!"),
_("The Citadel"),
_("Blackwind"),
_("Frozenpeak"),
_("Wildabar"),
_("Fountainhead"),
_("Vertigo"),
_("Winterkill"),
_("Nightshadow"),
_("Sandcaster"),
_("Spirit City"),
_("Olympus"),
_("Brindamoor"),
_("Burlock"),
_("The Royal Gardens."),
_("The Enchanted Forest."),
_("Before you may pass, the spirit guardian of this valley demands tribute."),
_("Lord Alberon"),
_("Drakonia"),
_("Gallavant"),
_("Xabran"),
_("Dragadune"),
_("Marsh Home"),
_("Orange stuff"),
_("Yellow stuff"),
_("green stuff"),
_("Lord Alberon calls you into his war room. He says, \"I am glad you have chosen to remain loyal to me, but this war is a terrible one for my kingdom. Already, the sorceress' towns to the Northeast have become unsure about their loyalties, and will not pledge allegiance to either side. This is hard on our cities as most of the wood in the land comes from these towns. We will need to recover their sawmills and take their towns by force.\""),
_("You are fighting on the side of your sister!"),
_("The Citadel"),
_("Dragontooth"),
_("Greywind"),
_("Blackwind"),
_("Wildabar"),
_("Winterkill"),
_("The Royal Gardens."),
_("The Enchanted Forest."),
_("Before you may pass, the spirit guardian of this valley demands tribute."),
_("Lord Alberon"),
_("Alamar"),
_("Blackfang"),
_("BoneVille"),
_("Knight stuff"),
_("New Dawn"),
_("Erliquin"),
_("Avone"),
_("Big Oak"),
_("Marsh Home"),
_("Frozenpeak"),
_("Spirit City"),
_("Drakonia"),
_("Gallavant"),
_("Your sister calls you before her altar in the morning. \"I have important news,\" she says, \"The barbarian kingdoms which border this land have agreed to lend us some of their castles and warriors in return for a share of the spoils. I hope victory comes swiftly, but your presence gives me strength to stand until whatever end awaits.\""),
_("\"First Blood\""),
_("You face three opponents in this scenario. Capture their castles and their heroes to prove your worthiness to Archibald."),
_("Nightshadow"),
_("Sandcaster"),
_("Brindamoor"),
_("Alamar"),
_("\"Barbarian Wars\""),
_("Brownston"),
_("Weddington"),
_("Whittingham"),
_("Westfork"),
_("Well placed bribes have won you a stronghold near the warring Barbarians. Be advised that given their proximity an unguarded castle is an open invitation to defeat."),
_("\"Necromancers!\""),
_("Timberhill"),
_("Fenton"),
_("Troy"),
_("Quick Silver"),
_("The Wizards who have captured the Necromancers' town have wasted no time in building defenses designed to stop you, and their last castle has just been completed. Fortunately only a Captain of the Guard and a small garrison are currently present.  If you hurry, you should be able to capture the castle before they have a chance to reinforce it!"),
_("\"Slay the Dwarves\""),
_("Dwarfhall"),
_("Perenor"),
_("Whiteshield"),
_("Stromhild"),
_("Greywind"),
_("Stromgild"),
_("Ostoroth"),
_("Ogrehild"),
_("Danger, Dragons abound!"),
_("Dwarf Hall, domain of the dwarf King."),
_("Tundara"),
_("Scouts report the enemy's stronghold lies to the Southwest. Our swift arrival has caught them by surprise. If you move quickly their resistance will be minimal."),
_("Sansobar"),
_("\"Betrayal!\""),
_("Long live Roland the true King!"),
_("Elk's Head"),
_("Cathcart"),
_("Pig's Eye"),
_("You have received a message from Archibald.  \" HOW DARE YOU BETRAY ME! I will see your head on the block alongside your new master's once I have won."),
_("Burton"),
_("\"Turning Point\""),
_("Long live Roland the true King!"),
_("Sherman"),
_("Cathcart"),
_("Pig's Eye"),
_("One of your \"Allies\" has joined Roland. You are now facing three castles, all belonging to the enemy. Good luck!"),
_("Blacksford"),
_("\"Peasants!\""),
_("Sorpigal"),
_("Weed Patch"),
_("Corlagon"),
_("Avalon"),
_("Hilltop"),
_("Yorksford"),
_("Elk's Head"),
_("Cathcart"),
_("There's a Wizard living in the north who is behind this peasant revolt."),
_("You have received a message from Archibald. \"General, these peasants deserve punishment. Put them to the sword and let Corlagon have his way with them.\""),
_("\"Dragon Master\""),
_("Dragon Watch"),
_("Dragon City lies beyond the Scorpion Hills."),
_("The guardians of Dragon Isle reside in the jungle."),
_("Powerful magic lies southwest of here in the Valley of the Kings."),
_("Your arrival here was a surprise to those sworn to guard Dragon Isle, and you were able to quickly capture one of their castles.  Use caution, though, for two other guardians remain in this jungle."),
_("Dragon Hill"),
_("Valley of the Kings."),
_("What is time spent poorly?"),
_("After a long search of the island, I have discovered that there is no way for me to escape without help.  I can not steal a ship from one of the coastal castles, and I dare not venture into the desert unless I wish to become Dragon food.  Should anyone find this, I beg of you, please send a ship and get me off this cursed island!  -Sir Christian"),
_("Bloodreign"),
_("\"Country Lords\""),
_("Pinehurst"),
_("Hillstone"),
_("Whiteshield"),
_("Bloodreign"),
_("Dragontooth"),
_("Greywind"),
_("Portsmith"),
_("Middle Gate"),
_("Vulcania"),
_("The North Road to Roland's castle."),
_("Sansobar"),
_("Atlantium"),
_("The country lords have allied and pooled their resources into one command. Not only have they massed their forces in the north, but they have sent a knight to the west to steal your supplies. Scouts report a castle to the east that would be ideal as a base of operations."),
_("\"The Crown\""),
_("Hilltop"),
_("Yorksford"),
_("Sherman"),
_("Elk's Head"),
_("Cathcart"),
_("Spies report Roland has sent a hero to search for the Crown. If he finds it first, all is lost!"),
_("Message from Archibald. \" Do not dare to return without my Crown.\""),
_("Pig's Eye"),
_("\"Greater Glory\""),
_("Weddington"),
_("Timberhill"),
_("Willow"),
_("Sheltemburg"),
_("Corackston"),
_("Blackridge"),
_("You have just 8 weeks to build your army and conquer a town on the other side of a distant river.  There are three paths to take, which will you choose?"),
_("Corlagon"),
_("Pinehurst"),
_("This way to the Necromancer Forest."),
_("You find an old signpost in the midst of a thicket that reads \"Warlock Wood, West.  Barbarian Fields, East.\""),
_("Middle Gate"),
_("Sansobar"),
_("Baywatch"),
_("Fountainhead"),
_("Nightshadow"),
_("Just 30 days left!"),
_("Just ONE week left!"),
_("\"Apocalypse\""),
_("Sandcaster"),
_("Lakeside"),
_("Olympus"),
_("Brindamoor"),
_("Burlock"),
_("Xabran"),
_("Dragadune"),
_("Kalindra"),
_("Algary"),
_("Avone"),
_("Hampshire"),
_("Chandler"),
_("South Mill"),
_("Weed Patch"),
_("Roc Haven"),
_("Avalon"),
_("Roland"),
_("Uncle Milty"),
_("Antioch"),
_("What are you doing here?"),
_("Do Not Enter!"),
_("Turn Back Now!"),
_("Abandon All Hope!"),
_("Welcome to your DOOM!"),
_("The Queen's Road."),
_("The Kings Road."),
_("You are now entering the domain of Prince Roland. Have a nice day."),
_("You are now entering the domain of Prince Roland. Have a pleasant stay."),
_("Archibald"),
_("Message from Archibald. \" General, thank you for bringing me this lovely gift. I have decided to participate directly in the capture of my brother Roland. Since your military advice has taken us this far, I will follow your orders to the letter.\""),
_("\"Force of Arms\""),
_("Pig's Eye"),
_("Quick Silver"),
_("There are three enemy castles to the north. Capture them in the name of Roland the true king!"),
_("Willow"),
_("Corackston"),
_("\"Annexation\""),
_("Westmoor"),
_("Willow"),
_("Blackridge"),
_("Pinehurst"),
_("You've received a message from Roland. \"In the absence of a strong leader, the local lords have fallen to fighting. Uniting this area is critical to our cause, so we must not fail.  Leaving your castle undefended in this highly contested region will surely lead to defeat. I'm counting on you.\""),
_("\"Save the Dwarves\""),
_("Perenor"),
_("Whiteshield"),
_("Stromhild"),
_("Greywind"),
_("Stromgild"),
_("Ostoroth"),
_("Ogrehild"),
_("Danger, Dragons abound!"),
_("Dwarfhall, Domain of the dwarf King."),
_("Tundara"),
_("Vulcania"),
_("Your forces are thinly spread in an effort to defend all the dwarf towns (which may not be transformed into castles). Consolidate your forces and smite the enemy before the towns fall."),
_("Dwarfhall"),
_("\"Carator Mines\""),
_("Vertigo"),
_("Winterkill"),
_("Nightshadow"),
_("Lakeside"),
_("Baywatch"),
_("Kalindra"),
_("Basenji"),
_("A gift of gold, m'lord, from the people of Enroth, to the people of Enroth.  Good luck, and may God save true King Roland!"),
_("Erliquin"),
_("Hampshire"),
_("This area is rich in resources. Explore, but beware, a castle left undefended will quickly fall."),
_("Chandler"),
_("\"Betrayal!\""),
_("Hilltop"),
_("Long live Roland the true King."),
_("Yorksford"),
_("Sherman"),
_("You have received a message from Roland. \" I am shocked! I had thought better of you, but I was terribly wrong. Now you'll have to live with your dark decision for the rest of your life.\""),
_("Cathcart"),
_("\"Turning Point\""),
_("Hilltop"),
_("Long live Roland the true King."),
_("Yorksford"),
_("Elk's Head"),
_("One of your \"allies\" has joined Archibald.  You now face an opponent with three castles to your one.  Good luck!"),
_("Cathcart"),
_("\"Defender\""),
_("Noraston"),
_("Sheltemburg"),
_("Blackridge"),
_("Woodhaven"),
_("Barbarian's castle lies to the south."),
_("Help!"),
_("Welcome to the sorceress' guild."),
_("Keep Out!"),
_("Condemned!"),
_("Fantasy Island."),
_("Murray's resort Isle!"),
_("For sale."),
_("Lord Halton"),
_("Wyrm"),
_("The Rock Store."),
_("King John"),
_("The islands have much wealth."),
_("There was a shipreck in the far east waters recently."),
_("Dragontooth"),
_("Crossroads"),
_("Vulcania"),
_("Sansobar"),
_("You've received a message from the guild. \"Thank God you've arrived! We're under seige from two enemies from the north and one from across the sea. Please save us, you're our only hope.\""),
_("Scouts report the notorious necromancer \"Wyrm\" has been sighted to the northeast."),
_("\"The Gauntlet\""),
_("You have just 8 weeks  to build your army and conquer a town on the other side of a distant river.  There are three paths to take, which will you choose?"),
_("Sandcaster"),
_("Lakeside"),
_("Olympus"),
_("Burlock"),
_("Alamar"),
_("Kalindra"),
_("Blackfang"),
_("Basenji"),
_("Sorpigal"),
_("Erliquin"),
_("Avone"),
_("Big Oak"),
_("Sorceress Forest.  Show respect for nature!"),
_("Knight's Trail."),
_("Wizardwood.  Magicians welcome!"),
_("Just 30 days left!"),
_("Just ONE week left!"),
_("\"The Crown\""),
_("Westfork"),
_("Hilltop"),
_("Yorksford"),
_("Sherman"),
_("Elk's Head"),
_("Archibald has also sent an army to find the Crown, you must find it first or all is lost."),
_("Message from Roland. \" We cannot hope to defeat Archibald without the Crown, I'm counting on you.\""),
_("Viper's Nest"),
_("\"Act of Desperation\""),
_("Viper's Nest"),
_("Pig's Eye"),
_("Blacksford"),
_("Burton"),
_("Blackburn"),
_("Lankershire"),
_("Timberhill"),
_("Havenwood"),
_("Corlagon"),
_("Roland"),
_("Message from Roland.  \"General, I have sent most of our troops and material ahead to the region of the final conflict with Archibald.  Unfortunately, Lord Corlagon has cut us off from the rest of our army.  I will be awaiting your victory in a castle across the west river.  I should be safe from attack.\""),
_("Lord Haart"),
_("Troy"),
_("\"Our Finest Hour\""),
_("Brindamoor"),
_("Burlock"),
_("Dragadune"),
_("Alamar"),
_("Kalindra"),
_("Blackfang"),
_("Algary"),
_("Sorpigal"),
_("New Dawn"),
_("Erliquin"),
_("Avone"),
_("Hampshire"),
_("Chandler"),
_("South Mill"),
_("Antioch"),
_("Brownston"),
_("Weddington"),
_("Archibald"),
_("Mr Ed"),
_("Archibald"),
_("Who is the true King?"),
_("Mr Ed"),
_("A Dragon, A Cyclops, or an Undead. King of the Centaurs, His name is ....?"),
_("Turn Back or DIE!"),
_("Turn Back Now or all will be LOST!"),
_("Restricted Area, Do Not Enter!"),
_("Trespassers will be EATEN!"),
_("Is it something I said? Go back and I will forget the whole thing."),
_("So you think you're smart?"),
_("Welcome to your DOOM!"),
_("Archibald is hiding at the end of the river."),
_("The River Styx"),
_("Roland"),
_("Message from Roland. \"General, circumstances permit me to take a hand in the events of this final conflict. I have your spoils of war with me and I will follow your advice explicitly.\""),
_("Corlagon"),
_("Deathgate"),
_("Capture the necromancer's dreaded castle \"Death Gate\" and free the land from the undead plague."),
_("Alamar"),
_("Bloodreign"),
_("Avalon"),
_("Sorpigal"),
_("Fenton"),
_("Sheltemburg"),
_("Dragontooth"),
_("Roscomon"),
_("Baywatch"),
_("DeathGate"),
_("Hillstone"),
_("Weed Patch"),
_("Greywind"),
_("Red player sympathizes with the undead cause."),
_("Decisions"),
_("Your town is undefended and your heroes are scattered.  Do you attack or defend?"),
_("Blackridge"),
_("Pinehurst"),
_("Woodhaven"),
_("Hillstone"),
_("Whiteshield"),
_("Bloodreign"),
_("Dragontooth"),
_("Greywind"),
_("Blackwind"),
_("Portsmith"),
_("Tundara"),
_("Vulcania"),
_("Boats my be needed to access some parts of this peninsula."),
_("Dominion"),
_("The King is dead, his kingdom has been shattered, and six leaders seek to seize power for themselves."),
_("Cathcart"),
_("Pig's Eye"),
_("Blacksford"),
_("Burton"),
_("Lombard"),
_("Fenton"),
_("Troy"),
_("Westmoor"),
_("Willow"),
_("Hillstone"),
_("Greywind"),
_("Blackwind"),
_("Portsmith"),
_("Sansobar"),
_("Nightshadow"),
_("Sandcaster"),
_("Lakeside"),
_("Brindamoor"),
_("Basenji"),
_("Algary"),
_("Sorpigal"),
_("Erliquin"),
_("Hampshire"),
_("South Mill"),
_("Roc Haven"),
_("Antioch"),
_("Brownston"),
_("Weddington"),
_("Westfork"),
_("Hilltop"),
_("Giants"),
_("What team won Super Bowl XXI and Super Bowl XXV?  (Hint... a Wizard might have these troops in his army)"),
_("Should this message ever reach home, please know that this has become a hostile place since the King's death.  No less than six factions are at war with each other, each seeking to be the King's successor.  Beware especially of the Barbarians and the Necromancers who control the north, their regions are easily defended and they have a wealth of gold and gems.  Do not venture to this land without a sizeable force.  -Sir Christian"),
_("The day you have feared has finally arrived.  The king, who you have faithfully served, has died, leaving no heir to his throne.  As his captain, you feel that this job should now be yours, but several factions even now are preparing for conquest.  You are at the center of the trade routes, having the sea to the south and the great forest to the north.  Go, now, Commander, and claim what is rightfully yours!"),
_("For years, you have existed peacefully in the Forest of Dreams, knowing that your king was the kindest and strongest ruler the land had seen in centuries.  Now, however, his reign is at an end, and there is no heir to succeed him.  You realize that a power struggle is coming, and that you must brace yourself for war, and prevent those who would harm this land from coming into power!"),
_("At last, the king is dead.  For years you have planned his demise, but now it is done, and there is no heir to take his place, though the Knights to the south believe that they are the rightful successors.  A wealth in wood (to the south) and ore (in the northern mountains) provides you with trade goods, and your isolation has allowed you to prepare your forces of darkness for this day.  Go, now, and fulfill your destiny!"),
_("Your isolation from the rest of the kingdom has largely kept you out of the political struggles, but now with the king's death, and lack of an heir, you see a golden opportunity to seize the throne for yourself.  Just remember that you have relied largely on trade for several key resources, especially sulfur, but with a little planning this land can be yours.  Go, now, and show these peasants how to rule!"),
_("For decades you have studied, learned, and allowed yourself to be ruled by that pitiful excuse for a king, knowing that one day the time would come for you to sit on the throne.  That time is now, for the king is dead and without an heir.  You have the advantage of isolation from the rest of the kingdom, but beware the miles of coastline that could leave you vulnerable to attack.  Go, now, and wipe your enemies from this land!"),
_("Living on the outskirts of the kingdom, you are considered an unwelcome outcast by the other leaders of the realm, though you always showed your support for the king.  Now, however, the king is dead, and many of those who spoke out againt him seek to seize his throne for themselves.  You have a vast desert at your back, rich with gems, and the advantage that many do not consider you a threat.  Go, now, and show them how wrong they are!"),
_("Anduran"),
_("Dragon's Eye"),
_("Your castle, founded inside the center of a mile wide crater, is besieged by those who desire your mineral wealth."),
_("Meramec"),
_("Pinehurst"),
_("Woodhaven"),
_("Hillstone"),
_("Whiteshield"),
_("Bloodreign"),
_("Portsmith"),
_("Middle Gate"),
_("Tundara"),
_("Vulcania"),
_("Sansobar"),
_("Dragon Rider"),
_("While away seeking the Ultimate Artifact, Kastor's kingdom is invaded!"),
_("Wildabar"),
_("Fountainhead"),
_("Kastor"),
_("Vertigo"),
_("Winterkill"),
_("Nightshadow"),
_("Sandcaster"),
_("Peasantsville"),
_("Orcville"),
_("Brindamoor"),
_("Burlock"),
_("Xabran"),
_("Fedx for comp"),
_("Dragon Wars"),
_("Three Warlocks in the land of Dragons. Lose thy home and all will be lost. Conquer thy enemies and the land shall forever be yours!"),
_("Lakeside"),
_("Brindamoor"),
_("Blackfang"),
_("Dragons Everywhere!"),
_("Antioch"),
_("Brownston"),
_("Weddington"),
_("Whittingham"),
_("Hilltop"),
_("Stick to the road!"),
_("Enroth"),
_("The land of Heroes II."),
_("Sandcaster"),
_("Lakeside"),
_("Olympus"),
_("Blackfang"),
_("Basenji"),
_("Erliquin"),
_("Big Oak"),
_("Stairs"),
_("the stairs"),
_("What goes up and down but never moves?"),
_("Westfork"),
_("Hilltop"),
_("Yorksford"),
_("Sherman"),
_("Roscomon"),
_("Elk's Head"),
_("Cathcart"),
_("Viper's Nest"),
_("Fool's Gold"),
_("A chance to end a bitter war has finally arrived as a new resource-laden land has been discovered."),
_("Weed Patch"),
_("Avalon"),
_("Weddington"),
_("Whittingham"),
_("Westfork"),
_("Hilltop"),
_("Yorksford"),
_("Sherman"),
_("Lord, messages have begun pouring in from our spies in the other island courts.  They have learned of a new volcanic island with vast amounts of reasources.  Your Majesty, with these new reasources we could put an end to a century of war between the islands, and reunite them under your rightful rule."),
_("Roscomon"),
_("Hurry, no time to wait.  This way to the dock."),
_("Keep going south"),
_("For Honor"),
_("The Red Tide of War rolls North.  Stopping the flood seems hopeless.  Yet, Honor demands you and your ally die trying."),
_("Hero's Hall"),
_("Avone"),
_("Big Oak"),
_("Chandler"),
_("South Mill"),
_("As you prepare your lands to fight the onslaught from the South, a curious message appears on your table in the Great Hall of your Castle.  Written in some ancient language, none but your sage can make any sense of it.  She promises to have the words deciphered by tomorrow..."),
_("The Table in the Great Hall of the Castle is Haunted."),
_("The Gods themselves will aid us in this War."),
_("Assassins tried to kill our ally."),
_("Roc Haven"),
_("Hilltop"),
_("As you break your fast your sage rushes in, \"Good news, my lord!  I have translated the message.  Two great heroes were imprisoned many years ago.  They lie sleeping - still guarded by magic barriers and monsters.  My lord, they lie nearby- in between our ally and us.  If we could free them, they would surely aid us against our enemies!  The password to the first magic barrier can be learned at the Aqua Traveller's Tent.\""),
_("North Road"),
_("North Road"),
_("Your Scouts report that the Aqua Traveller's Tent is located along The North Road."),
_("The Gold Traveller's Tent is near the Aqua Taveller's Tent."),
_("Your Scouts report talking to a young knight, a squire to the two sleeping heroes.  The squire is trapped by the Aqua Magic Barriers and a group of fallen Paladins.  He says the two heroes, Dainwin and Ceallach, have awakened but are still trapped by a Gold Magical Barrier and asks your aid in freeing them."),
_("Yorksford"),
_("Sherman"),
_("Ceallach"),
_("Dainwin"),
_("After you return from a scouting trip, your Seneschal hurries to greet you.  \"My Lord, in your absence I signed an agreement in your name with a Master Merchant.  If we supply him with the resources he needs, through trading, he can return the resources to us in a week or so, plus some additional ones.\"  The Seneschal eyes you anxiously.  You hesitate, then nod slowly, \"Good, we can use more resources>\""),
_("The Master Merchant arrives and takes the resources he needs for trade.  Plus a little gold for expenses..."),
_("The Master Merchant arrives at your Castle.  He tells you tall tales of travel, full of outrageous lies.  He also gives you, your share of the profits..."),
_("The Master Merchant arrives and takes the resources he needs for trading.  Plus a little more gold for expenses..."),
_("The Master Merchant arrives back at your Castle.  He tells you tall tales of faraway places full of outrageous lies.  He also gives you, your share of the profits..."),
_("Forsaken Lands"),
_("A legion of peasants stands between you and this unclaimed island."),
_("Burton"),
_("Blackburn"),
_("Lankershire"),
_("Fenton"),
_("Forder Oaks"),
_("Westmoor"),
_("Willow"),
_("Sheltemburg"),
_("Federal express, when it absolutely positively has to be there turn one."),
_("Pinehurst"),
_("Hillstone"),
_("Bloodreign"),
_("Dragontooth"),
_("Fortress Isle"),
_("Four players must work together to assault the Wizards' Stronghold."),
_("Lombard"),
_("Troy"),
_("Meramec"),
_("Quick Silver"),
_("Westmoor"),
_("Middle Gate"),
_("Tundara"),
_("Vulcania"),
_("Sansobar"),
_("Atlantium"),
_("Baywatch"),
_("Wildabar"),
_("Fountainhead"),
_("Vertigo"),
_("Nightshadow"),
_("Sandcaster"),
_("Lakeside"),
_("Olympus"),
_("You uncover a compass in the grass!"),
_("Brindamoor"),
_("You have found what someone else has lost..."),
_("Burlock"),
_("A glint by a tree catches your eye..."),
_("In the stream you find an old compass!"),
_("Xabran"),
_("Some gems!"),
_("A piece of crystal!"),
_("A bit of mercury!"),
_("A cache of sulfur!"),
_("A bit of crystal!"),
_("A quantity of mercury!"),
_("A couple of gems!"),
_("A cache of mercury!"),
_("A handful of gems!"),
_("A lump of crystal!"),
_("A cache of sulfur!"),
_("A bit of mercury!"),
_("A couple of gems!"),
_("A cache of crystal!"),
_("Some sulfur!"),
_("A bit of mercury!"),
_("A cache of sulfur!"),
_("A quantity of crystal!"),
_("A pile of gems!"),
_("A lump of mercury!"),
_("A gold chunk!"),
_("A gold cache!"),
_("A lump of gold!"),
_("A pile of gold!"),
_("A gold nugget!"),
_("A bit of mercury!"),
_("Some ore!"),
_("A quantity of sulfur!"),
_("A pile of crystal!"),
_("A gold nugget!"),
_("A cache of gems!"),
_("A bit of mercury!"),
_("A chunk of ore!"),
_("Some sulfur!"),
_("A lump of crystal!"),
_("A cache of gold!"),
_("A pile of gems!"),
_("A quantity of mercury!"),
_("A chunk of ore!"),
_("A bit of sulfur!"),
_("Some crystal!"),
_("A chunk of gold!"),
_("Some ore!"),
_("A handful of gems!"),
_("Blackfang"),
_("Algary"),
_("Sorpigal"),
_("Full House"),
_("Start with five castles!  How could you lose!?  Oh yeah, everyone else starts with five, too."),
_("No Trespassing"),
_("Sherman"),
_("Cathcart"),
_("Westmoor"),
_("Willow"),
_("Sheltemburg"),
_("Corackston"),
_("Pinehurst"),
_("Woodhaven"),
_("Hillstone"),
_("Whiteshield"),
_("Bloodreign"),
_("Dragontooth"),
_("Greywind"),
_("Blackwind"),
_("Portsmith"),
_("Middle Gate"),
_("Tundara"),
_("Vulcania"),
_("Sansobar"),
_("Atlantium"),
_("Baywatch"),
_("Wildabar"),
_("Fountainhead"),
_("Vertigo"),
_("Nightshadow"),
_("Sandcaster"),
_("Lakeside"),
_("Olympus"),
_("Brindamoor"),
_("Burlock"),
_("Xabran"),
_("Dragadune"),
_("Alamar"),
_("Kalindra"),
_("Blackfang"),
_("Basenji"),
_("Algary"),
_("Sorpigal"),
_("No Fishing!"),
_("New Dawn"),
_("Erliquin"),
_("Avone"),
_("Big Oak"),
_("Hampshire"),
_("Chandler"),
_("Weed Patch"),
_("Avalon"),
_("Good vs. Evil"),
_("The Gods have given you 6 months to prove yourself. Good or Evil - who shall prevail? (Blue,Green and Red vs Yellow, Orange and Purple)"),
_("Lakeside"),
_("Mayland"),
_("Horizon"),
_("Blackburn"),
_("Mountainview"),
_("Bayside"),
_("Tacma"),
_("Dirt"),
_("Forestria"),
_("Erliquin"),
_("Corackston"),
_("Blackridge"),
_("Pinehurst"),
_("Hillstone"),
_("Whiteshield"),
_("Bloodreign"),
_("Ye old fish liver oil."),
_("Dragontooth"),
_("Greed"),
_("After centuries of friendship, the Wizards have suddenly decided to stop sharing their Library with the rest of the world.  This can't be good!"),
_("Greywind"),
_("Portsmith"),
_("Middle Gate"),
_("Tundara"),
_("Vulcania"),
_("Baywatch"),
_("Wildabar"),
_("Fountainhead"),
_("Nightshadow"),
_("Sandcaster"),
_("Lakeside"),
_("You come across the dead remains of what was appearantly a powerful wizard!  You wonder if it's safe to continue."),
_("Remains of a long since dead wizard have attracted an ancient artifact.  This artifact has now attached itself to you!"),
_("The mage wars have caused great turmoil.  This island has become a central flux of magical power.  Be wary all those that enter upon here."),
_("The mage wars have caused a great turmoil.  This island has become a central flux of magical power.  Be wary all those that enter upon here."),
_("It is obvious that the mage that once was here had won many battles!  There, upon his hand, is a most powerful ring!"),
_("Many years ago, a couple of mages had a \"duel\" that forever changed the lake at the center of this continent.  Hearty adventurers might find interesting treasure there!"),
_("For centuries, the Wizards of the North have maintained a vast library for all the world to share.  Now, however, they have closed their doors, and issued declarations of war to each of the other rulers of the land.  To make matters worse, rather than ally with you to face the Wizards, each of the others have decided to go forth on their own in an effort to conquer this land for themselves!  Prepare your forces, commander, for you now stand alone."),
_("The four factions race to capture a mystical castle."),
_("Blackwind"),
_("Tundara"),
_("Vulcania"),
_("Sansobar"),
_("Astircaer"),
_("The First One To Take Astircaer Wins!"),
_("The First One To Take Astircaer Wins!"),
_("The First One To Take Astircaer Wins!"),
_("The First One To Take Astircaer Wins!"),
_("I Would Go That Way If I Were You."),
_("NO, Not That Way. This Way."),
_("There's a warm wind blowing from the south."),
_("Many years ago, a falling star crashed near here.  Only now the area is safe enough to explore.  Rumor has it a castle exist where the star fell."),
_("Guardian War"),
_("You and your ally's families were given custody of The Isle of Knowledge.  Other Lords feel the time has come for new guardians..."),
_("Algary"),
_("Erliquin"),
_("Isle of Knowledge"),
_("Hampshire"),
_("Chandler"),
_("Gate to The Isle of Knowledge"),
_("Gate to the Isle of Knowledge"),
_("Weed Patch"),
_("The Scholars, Priests, and Priestesses of the Isle have given you what they can to help you defend against your enemies."),
_("The Scholars, Priests, and Priestesses of the Isle have given you what they can to help you against your enemies."),
_("Road to Isle of Knowledge"),
_("Road to the Isle of Knowledge"),
_("Roc Haven"),
_("The Southern Witch is biding her time.  She will strike when your armies are weak."),
_("The Yellow Lord is a hothead who will attack before his allies can send him aid."),
_("The people on the Isle of Knowledge are taking up a collection to aid us."),
_("You found Treasure!"),
_("You found Treasure!"),
_("There is hidden treasure south of the Blue Lord's Sawmill."),
_("There is hidden treasure north of the Green Lord's Ore Mine."),
_("The Yellow Lord has the Ultimate Artifact."),
_("Our ally was greatly weakened when his resources were plundered."),
_("Reports from your spies tell of enemies on the march.  As you rush to the castle courtyard to prepare your armies, you are intercepted by your Chaplain.  \"My Lord, I have received word that we should send what Heroes we can to the Isle of Knowledge.   The Scholars there have agreed to teach them so they will be strong for the battles ahead of us.\"  You thank the Chaplain for the information and head thoughtfully into the courtyard."),
_("Avalon"),
_("Five heroes vie for control of a familiar land."),
_("Blackfang"),
_("Algary"),
_("Avone"),
_("Roscomon"),
_("Viper's Nest"),
_("Hot Spot"),
_("When you're ready, take the teleport to the Island's Hot Spot!"),
_("Yorksford"),
_("Elk's Head"),
_("Cathcart"),
_("Viper's Nest"),
_("Beyond the door, there be Dragons. BEWARE!"),
_("Beyond the door, there be Dragons. BEWARE!"),
_("Hail Unicorns!"),
_("This twisted maze of sorceress towns has three factions struggling for sole control.  Use your resources wisely!"),
_("Sorpigal"),
_("New Dawn"),
_("Big Oak"),
_("South Mill"),
_("Weddington"),
_("Whittingham"),
_("Hilltop"),
_("Roscomon"),
_("Elk's Head"),
_("Pig's Eye"),
_("Isle Maze"),
_("Remember, you're searching for the Ultimate Artifact... don't get distracted!"),
_("Gavonshire"),
_("Sundune"),
_("Wilasher"),
_("Sirein"),
_("Dear Diary,                           I found a mermaid today.  She was floating in a patch of seaweed next to a rock.  A very friendly sort of creature too!  Gave me all sorts of lovely gems and jewelry!  She said to come back again sometime for more of the sea riches.  Wow. Ahab"),
_("A splash in the seaweed alerts you to a mermaid waving in a friendly manner. \"Oh, I thought you were Ahab.\" She is surprised, but quickly composes herself. \"Well, if you meet him, give him these treasures I have collected.\""),
_("The crew are unworthy!  I am not going down with the ship! -The Captain"),
_("425 bottles of beer on the wall, 425 bottles of beer! If one of those bottles should happen to fall, there'll be..."),
_("Mutiny!  The crew has dumped off my precious cargo into the sea!  Thank goodness it floats - when I've rid of them, I'll come back to pick it up!"),
_("I didn't do it!"),
_("A three hour tour, a three hour tour..."),
_("One of your loyal subjects, a fairy tells you where to find a cache of mercury!"),
_("Somebody has stuffed a pile of gems in the ditch!"),
_("A tiny gnome points to a chunk of crystal you otherwise would have overlooked!"),
_("Wow, somebody has left a pile of wood here!"),
_("One of your loyal goblins has brought you an armload of crystal!"),
_("What's this? A pile of gems?"),
_("Cathcart"),
_("Viper's Nest"),
_("What's this? Someone has left a pile of wood here!"),
_("In the hole you find a chunk of ore!"),
_("Blacksford"),
_("A friendly dolphin splashes alongside the ship."),
_("Jolly Roger was here"),
_("You see something that could just be the elusive Nubbie!"),
_("On quite days, Nubbie the sea monster can be seen!"),
_("Pet Cemetary"),
_("Pirate's Cove"),
_("A ghostly pirate ship appears and sails on by."),
_("The winds howl in mourning around the shipwreck."),
_("A dolphin playfully jumps into the air."),
_("Swimming near the kelp is a pod of dolphins."),
_("A flock of seagulls circle overhead."),
_("An albatross flies ahead of the ship for a while"),
_("Spy Tower - see what your competition is doing!"),
_("Do not remove coins from fountain."),
_("No swimming."),
_("We'll join you - for the right price."),
_("The roars of several dragons echo from the towers."),
_("A flight of dragons circles overhead."),
_("Someone is playing a pan flute around here."),
_("Beware the sirens!!!"),
_("King of Death"),
_("Find and destroy the evil beings who rule the wastelands."),
_("Lakeside"),
_("Sherman"),
_("Brindamoor"),
_("Burlock"),
_("Spector"),
_("Dragadune"),
_("Lost Continent"),
_("Six factions have established a foothold on a huge, unexplored continent.  Can you eliminate the other five?"),
_("Big Oak"),
_("Sandcaster"),
_("Vertigo"),
_("Pig's Eye"),
_("You have been ordered here to claim this land in the name of your King and recover any riches that you might find.  However, five other Kings and Queens have also sent their heroes to this land, so you must watch out for them as well as the natives!"),
_("Hungry dragons await.  Welcome, food."),
_("You are a fool to come here!"),
_("Turn back, friend, while you still can!"),
_("When you think yourself invincible, walk through this gate.  Even then, prepare to meet your bitter end."),
_("You will need a stronger army than that, mortal, to step through this portal."),
_("Beyond here be Dragons!"),
_("Dragon Hill"),
_("Greywind"),
_("Dragon City"),
_("Roscomon"),
_("Sherman"),
_("Dragonburg"),
_("Meramec"),
_("Whittingham"),
_("Weddington"),
_("Dragon Watch"),
_("Hillstone"),
_("Whiteshield"),
_("A supply ship has arrived from the homeland!  You send word home that all is well."),
_("Bloodreign"),
_("Olympus"),
_("Dragonville"),
_("Dragon Town"),
_("Sansobar"),
_("Baywatch"),
_("Woodhaven"),
_("Brindamoor"),
_("Burlock"),
_("Xabran"),
_("Alamar"),
_("Kalindra"),
_("New Dawn"),
_("Erliquin"),
_("Hampshire"),
_("South Mill"),
_("Roc Haven"),
_("Lost Relic"),
_("The gods have granted this world a great artifact, to find it means victory."),
_("Pinehurst"),
_("Beware of thieves!"),
_("Robbers have looted your treasury, stealing valuable resources."),
_("Robbers have looted your treasury and you have lost valuable resources."),
_("Your treasury has been looted by robbers and you have lost valuable resources."),
_("Your treasury has been looted by robbers and you have lost valuable resources."),
_("Robbers have looted your treasury and you have lost valuable resources."),
_("Robbers have looted your treasury and you have lost valuable resources."),
_("Arr' Here be pirates gold buried."),
_("Ah, you stumble across something buried in the sand.  As you dig it up you discover a small pile of gems and crystal."),
_("It is said that King Zealot found the gods' artifact once and it let him rule for 100 years."),
_("The ancient King Zealot had the artifact of the gods and then hid it in his old age so that it could not be used by others."),
_("Kalindra"),
_("New Dawn"),
_("Blackwind"),
_("Corackston"),
_("Blacksford"),
_("Troy"),
_("Bloodreign"),
_("Forder Oaks"),
_("Woodhaven"),
_("Dragadune"),
_("Viper's Nest"),
_("Bridge Out!"),
_("Turn Back or else!"),
_("Road Ends"),
_("Pig's Eye"),
_("Meramec"),
_("Westmoor"),
_("Willow"),
_("It has become apparent that if all your enemies were eliminated, you would have all the time you need to find the Ultimate Artifact."),
_("Magic Three"),
_("Seek out the Ultimate Artifact to be victorious in this strangely shaped land."),
_("Hawkins"),
_("Galveston"),
_("Portsmith"),
_("Eatio"),
_("Gate"),
_("Vulcania"),
_("Sansobar"),
_("Baywatch"),
_("Wildabar"),
_("Fountainhead"),
_("Might vs. Magic"),
_("Play the Knight or Barbarian in an alliance in this classic duel against the four spell casters. (Blue and Green vs Red)"),
_("Dragontooth"),
_("Baywatch"),
_("Vertigo"),
_("Winterkill"),
_("Dragadune"),
_("Erliquin"),
_("Burton"),
_("Lankershire"),
_("Brownston"),
_("Weddington"),
_("Sherman"),
_("Roscomon"),
_("Elk's Head"),
_("Viper's Nest"),
_("Mineral Wars"),
_("All mines are grouped by type. Trade is your only hope."),
_("Sherman"),
_("You see the remains of a burned out sawmill here.  All you can salvage is some ofwood left for scrap."),
_("There used to be a mine here, but it has long since run out of ore.  You are only able to scavenge 5 units of ore from the old site."),
_("Elk's Head"),
_("Cathcart"),
_("Pig's Eye"),
_("Blacksford"),
_("Burton"),
_("It looks like there used to be an ore mine here but all you see now is a hole in the ground and some minerals scattered around."),
_("You see the remains of an old sawmill just to realize that it will no longer produce.  You gather the ramains and move on."),
_("You see the remains of an old sawmill, but it is obvious that you will not be able to make it work again."),
_("This spot overlooks an old quarry.  This was one of the only places in the world where ore could be taken right out of the ground.  Unfortunately the jungle has reclaimed the quarry and it is unusable.  You collect the last of the ore and depart."),
_("A Gift from your King, and a note that reads \"Use these resources wisely, It's all we have left\"."),
_("Lombard"),
_("Timberhill"),
_("fedx comp"),
_("Mountain king"),
_("It's windy at the top.  Defend, Divide, and Conquer."),
_("Viper's Nest"),
_("Sandcaster"),
_("Hilltop"),
_("Middle Gate"),
_("Pinehurst"),
_("New Enemies"),
_("With the year long eruption of Mt. Kitisland, your three worst enemies now have a ground bridge to your eastern contenent."),
_("Hilltop"),
_("Yorksford"),
_("Roscomon"),
_("Pirites strike and take the gold from you holds."),
_("Cathcart"),
_("Viper's Nest"),
_("Welcome to the wounderous Kitisland range.  Eruptions each day, beware of dragons."),
_("Pig's Eye"),
_("Blacksford"),
_("Burton"),
_("Blackburn"),
_("Lankershire"),
_("Lombard"),
_("Timberhill"),
_("Fenton"),
_("Beware, the whirlpool may not take you into a friendly embrace."),
_("You, recieve word that you have been robbed."),
_("You see the mast of ancient ship here.  On further investigation you find that the ships holds are full of gems.  The hours pass as your crue liberates the treasure."),
_("Your horse stumbles and throws you from the saddle.  When you awaken you find that you have hit your head on the Fizbin of Misfortune."),
_("While traveling a mesenger meets you on the road.  His message tells of a new ally from an island far to the south.  This ally can not offer forces to your battle but has agreed to send some support in the form of gold and crystal."),
_("A bandit army of gorgons jump you without warning.  they stone your entire army demand 500 gold before they will release your comrads.  Realizing that it is much cheeper to pay then rebuild your army you part with the gold."),
_("North vs. South"),
_("It's a battle for supremacy as the Blue and Green heroes take on Red and Orange in team competition!"),
_("Alamar"),
_("Kalindra"),
_("Algary"),
_("Chandler"),
_("Roc Haven"),
_("Antioch"),
_("Weddington"),
_("Whittingham"),
_("Westfork"),
_("Hilltop"),
_("Someone has stolen gold and resources from  the palace treasury!  You suspect your enemies, but you can't know for certain."),
_("Overlord"),
_("The Overlord has given you 4 months to conquer this land or deliver to him the sum of 150,000 gold."),
_("Dragontooth"),
_("Greywind"),
_("Blackwind"),
_("Portsmith"),
_("Middle Gate"),
_("Tundara"),
_("Vulcania"),
_("Sansobar"),
_("Beware the rocks"),
_("You run aground on the rocks and have to use some wood to fix your boat."),
_("Fountainhead"),
_("Message from Overlord. \"WHERE'S MY GOLD?\""),
_("Message from Overlord. \"STILL WAITING FOR MY GOLD!\""),
_("Final message from Overlord. \"The royal executioners are on their way. My gold, the land or your head- it's your choice.\""),
_("Pandemonium"),
_("The King will sell you this land for 200,000 gold or you can take it by force. The choice is yours."),
_("Alamar"),
_("Kalindra"),
_("Blackfang"),
_("Basenji"),
_("Buried Treasure!"),
_("Buried Treasure!"),
_("Buried Treasure!"),
_("Buried Treasure!"),
_("Buried Treasure!"),
_("My leige, we have established a foothold (which we cannot afford to lose) and all of our Heroes have joined us. The king has made us the offer to purchase this land for 200,000 gold or we may take it by force. The local lords have been fighting and each wants to be the one that defeats us. Now all the local armies have arrived on the beach, creating a state of complete Pandemonium!"),
_("Peasants"),
_("Complete"),
_("Help peasant farmers regain their castle and land, else they'll take your crops."),
_("Westfork"),
_("You hear a low rumble, look up and see an avalanche!  You dive onto a large patch of grass to avoid it.  While dusting yourself off, you consider yourself quite lucky to be alive.  Luckier still to find a Four-Leaf Clover stuck on your nose."),
_("Troy"),
_("Pig's Eye"),
_("For information about Ye Rich lands to the south, speak to Alponse at the Golden Goose Tavern. Excellent views, plentiful water."),
_("Avalon"),
_("You've saved a group of miners from the dragons.  One of them approaches you, \"Thank you so much for saving us!  We found this sulfer and sword in the mine, then those dragons chased us!  I don't know how much longer we could survive!\""),
_("A group of peasant farmers approach you, \"We are in dire need of your assistance. Our castle to the east has been overrun and our Lord killed. Please help us regain our homes! There are still women and children there! Take what we have to help!\""),
_("Your advisor approaches you with some startling information, \"My liege, the peasants are draining us. They do nothing, and take everything! We must get them home. Your own citizens are beginning to suffer!\""),
_("Your advisor approaches you, \"My liege, something must be done about these peasants! They still refuse to work.  At this rate you won't have anything to put in your daughter's dowry!\""),
_("Your advisor approaches you with a long face, \"My liege, the peasant's numbers are growing steadily.  All they do is take, take, take! We are beginning to suffer dearly because of them.\""),
_("Your advisor approaches you smiling greatly, \"My liege! The peasants are making money in the market, and are finally paying taxes!\""),
_("A man is laying on the ground, near death. He looks to you and speaks, \"Please help my companions! Please... they can't...cough...get away from...cough...the drag...\" With that, he dies."),
_("Detour! Mountain pass to the East has been known to have avalanches! For your own safety, follow the road South."),
_("Woodhaven"),
_("Portsmith"),
_("Middle Gate"),
_("Tundara"),
_("Vulcania"),
_("A group of peasant farmers approach you, \"We are in dire need of your assistance.  Our castle to the east has been overrun and our Lord killed.  Please help us regain our homes!  There are still women and children there!  Take what we have to help!\""),
_("A group of peasant farmers approach you, We are in dire need of your assistance.  Our castle to the northeast has been overrun and our Lord killed.  Please help us regain our homes!  There are still women and children there!  Take what we have to help!\""),
_("A group of peasant farmers approaches you, \"We are in dire need of your assistance.  Our castle to the north has been overrun and our Lord killed.  Please help us regain our homes!  There are still women and children there!  Take what we have to help!\""),
_("Pirate Utopia"),
_("The Fortune of Infamous Uae was buried on one of these islands. She died without ever revealing it.  Find it before the other cutthroats."),
_("Corackston"),
_("Hillstone"),
_("Blackwind"),
_("Middle Gate"),
_("Baywatch"),
_("Uae was the scurviest, pirate ye'd never wanta see. In all her years of murdering and thieving she amassed so much ill-gotten booty that she couldn't carry it around in her galleon.  Besides, even the meanest can't stay awake all the time.  Legend tells that she hid it so well, she was thinking that she just might forget where it was.  So she left clues around the islands, carved in stone.  Well, she's dead now.  It's up to you to recover her legacy."),
_("What's another word for pirate treasure?"),
_("Ice Palace"),
_("My Treasure Is Buried Beneath Three Palm Trees"),
_("What is the Sum of all Numbers from 1 to 200?"),
_("As you approach the gates of the Ice Palace, one of your troops points in terror.  You watch in awe as great slabs of ice separate from the castle walls with loud cracking reports and crash to the ground.  Soon the ice is gone and the sun begins to peak through the gloom.  The deathly silence that must have ruled these lands for centuries ends as birds begin to sing.  From inside you hear the sounds of life."),
_("Above you looms the ancient Ice Palace.  Dimly remembered myth speaks of a Prince who rejected the advances of the Winter Goddess, and thus he and his domain were cursed to remain shrouded in ice, hidden in a forgotten corner of the world.  It is said that he can only be rescued by a hero who is both clever and bold.  Are you that one?  Do you dare enter this frozen domain?"),
_("What?  What's this?  Something at the bottom of this pool..."),
_("Xabran"),
_("Abandon All Hope Ye That Enter Here"),
_("Kalindra"),
_("Blackfang"),
_("Basenji"),
_("Algary"),
_("Wicked Warlock Way"),
_("Secret Mountain Pass"),
_("Your troops begin to wonder about your sanity."),
_("Your crew begins to grumble."),
_("\"Why have we come this way?\"  asks the first mate.  You have no answer."),
_("Morale becomes even lower as the endless cliffs move past."),
_("Your crew seriously entertains thoughts of mutiny.  Your nights are sleepless."),
_("\"We are at the edge of the world!\"  they scream.  \"What are we doing here?\""),
_("Goblin Island"),
_("Goblin King"),
_("Sorpigal"),
_("The Lost Castle of the Ancients"),
_("What everyday word is most often pronounced incorrectly?"),
_("The End of the World is Nigh!"),
_("The End of the World is Nigh"),
_("Hampshire"),
_("Maelstrom of Deceit"),
_("Rendall Koski was here. 1997.  Northampton, Massachusetts There is a powerful artifact in the southeastern corner of the world.  Go for it, explorer!"),
_("Roc Haven"),
_("Avalon"),
_("Ice Prince"),
_("The Proving Grounds"),
_("Whittingham"),
_("Beware the Domain of Dragons"),
_("Beware the Dragon Leader"),
_("Westfork"),
_("The Realm of Air is barred, but you may appeal here for help."),
_("The Wasteland"),
_("Gaurdian"),
_("Lladner Dock"),
_("Sherman"),
_("Elk's Head"),
_("Fire King"),
_("Turn back, you fool."),
_("You should turn back."),
_("One of your troops stubs its paw on something buried here.  After a few hours of digging you unearth a cache of treasure!"),
_("The Ice Prince stands frozen in some forgotten corner of the world."),
_("The Fire King is an ally to the dragons, and will help a friend of theirs."),
_("The Island of Lost Reason"),
_("The Retreat of the Alchemist Doctor Yu"),
_("Viper's Nest"),
_("Maelstrom of Misery"),
_("If three heroes could dig six holes in three days, how long would it take six heroes to dig twelve holes?"),
_("Pig's Eye"),
_("Portals"),
_("You can only reach your enemies via teleporters, but each jump is a leap of faith."),
_("Burlock"),
_("Xabran"),
_("Dragadune"),
_("Alamar"),
_("Kalindra"),
_("Basenji"),
_("Sorpigal"),
_("New Dawn"),
_("Erliquin"),
_("Hampshire"),
_("Chandler"),
_("South Mill"),
_("Weed Patch"),
_("Roc Haven"),
_("Avalon"),
_("Look before you leap."),
_("Many that have gone through this door have never returned."),
_("What's behind door number one?"),
_("These doors are a risk the likes of which you do not know."),
_("Pyramid"),
_("Your opponents are allied against you and each is twice as powerful as his predecessor! Is it possible to win?"),
_("New Dawn"),
_("Whittingham"),
_("Westfork"),
_("Hilltop"),
_("Yorksford"),
_("Sherman"),
_("Roscomon"),
_("Elk's Head"),
_("Pig's Eye"),
_("Revolution"),
_("You've ruled with an iron fist (and an army of undead), but now your kingdom has turned against you!"),
_("Blackwind"),
_("Portsmith"),
_("Middle Gate"),
_("Sansobar"),
_("Wildabar"),
_("Fountainhead"),
_("Nightshadow"),
_("Lakeside"),
_("Blackburn"),
_("Burlock"),
_("Xabran"),
_("Dragadune"),
_("Kalindra"),
_("Blackfang"),
_("For years, you've been able to keep your subjects \"appeased.\"  Now however, you discover not only that your entire kingdom has turned against you, but most of your outer towns have fallen to the different factions.  To make matters worse, all your gold suddenly seems to be missing from the treasury!"),
_("Algary"),
_("Erliquin"),
_("Sandro"),
_("Basenji"),
_("Rumors abound and your faithful hero Sandro is now highly regarded by the masses. Should Sandro desert you, all will be lost."),
_("River Crossing"),
_("Your castle is the last outpost in the area, Don't lose it!"),
_("Antioch"),
_("South Mill"),
_("Timberhill"),
_("Burlock"),
_("Our reinforcements were lost in a storm, we salvaged all we could!"),
_("Sands of Time"),
_("A desert isle rich in resources rewards the quick.  Just be sure to watch your back!"),
_("Hampshire"),
_("Roc Haven"),
_("Avalon"),
_("Antioch"),
_("Brownston"),
_("Danger a whirlpool destroyed my ship."),
_("Entering the high desert"),
_("Entering the desert high"),
_("Entering high in the desert"),
_("Entering the higher desert"),
_("Weddington"),
_("Whittingham"),
_("Yorksford"),
_("Scorched Earth"),
_("An enemy from across the sea has seized half your towns.  Can you put aside your own feud with your brother to fight this common enemy?"),
_("Blackwind"),
_("Vertigo"),
_("Winterkill"),
_("Lakeside"),
_("Willow"),
_("Burlock"),
_("Kalindra"),
_("Blackfang"),
_("Basenji"),
_("Many years ago, your father, the King, died in a freak hunting accident.  Since then, you and your brother have jointly ruled his kingdom, but both of you have been seeking a way to seize the throne for yourself.  You got your wish.  Attackers from across the sea have captured more than half your towns and castles, effectively dividing the continent in two.  Now is the time to repel these invaders and do away with your brother once and for all!"),
_("A merchant caravan arrives, bringing gold and supplies, however, no one can seem to remember where they came from.  You silently praise this anonymous benefactor and continue your duties."),
_("Seasons Change"),
_("None of the four leaders like being stuck in a land that has only one season."),
_("Slippery when wet."),
_("Elk's Head"),
_("Cathcart"),
_("Viper's Nest"),
_("Pig's Eye"),
_("Seven Lakes"),
_("Plenty of resources and lots of ground to cover. Watch out for Orange and Purple!"),
_("Lakeside"),
_("Olympus"),
_("Lankershire"),
_("Burlock"),
_("Xabran"),
_("Dragadune"),
_("Kalindra"),
_("Sorpigal"),
_("Corackston"),
_("Erliquin"),
_("Winterkill"),
_("New Dawn"),
_("Blackwind"),
_("Basenji"),
_("Welcome to Power Island. He who controls this Isle controls the Seven Lakes!"),
_("Alamar"),
_("Weed Patch"),
_("What walks in the morning on four legs, two in the afternoon and three in the evening?"),
_("What is always coming but never arrives?"),
_("What cannot be seen but only heard, and will not speak until spoken to?"),
_("The more there is the less you see."),
_("Four lakes have castles, three have treasure."),
_("Who am I?"),
_("Find the center island."),
_("Where am I?"),
_("Whittingham"),
_("Shipwrecked!"),
_("Your expedition has taken a turn for the worse... you now have no way to get home!"),
_("New Vertigo"),
_("Middle Gate"),
_("Erliquin"),
_("Sansobar"),
_("Wildabar"),
_("Baywatch"),
_("Viper's Nest"),
_("Your Queen sent you here to explore this newly discovered territory, but a freak storm scattered your fleet and left you stranded.  You gather the survivors and form a small settlement, naming it New Vertigo.  This place is your home now, and survival is your highest priority, but remember, if you are captured or killed, it's over!"),
_("Your scouts return with grim news.  The natives of this land are currently at war with each other, and they like outsiders even less than they like each other!  Congratulations, Commander, you're at war!"),
_("Beware of Warlocks"),
_("Tundara"),
_("What good fortune!  You've discovered a long-abandoned settlement.  To your surprise, you discover that the previous inhabitants left some of their resources behind when they departed!"),
_("Beware of Warlocks"),
_("Sherman"),
_("Pinehurst"),
_("Hillstone"),
_("DANGER!  QUICKSAND!"),
_("Whiteshield"),
_("Dragontooth"),
_("Greywind"),
_("Realm of the Undead.  Fresh blood welcome."),
_("Realm of the Undead.  Fresh blood welcome."),
_("No tresspath...  No tree...  No thresh...  GO AWAY!"),
_("GO AWAY!"),
_("Sharkania"),
_("Four kingdoms race to capture the island of Sharkania."),
_("Crossroads North"),
_("Weed Patch"),
_("Sharkania"),
_("Crossroads South"),
_("Brownston"),
_("Whittingham"),
_("Yorksford"),
_("They say there's mermaids in these waters..."),
_("Welcome to Li'l Alctatraz! Vistors NOT welcome."),
_("Log go up... Log go down... Log go up... Log go down...  OOoohhhhhhhh........"),
_("If you free a hero, they may help..."),
_("Have fun storming the castle!"),
_("Skirmish"),
_("You will clash quickly on this small head-to-head map, so stay on your toes!"),
_("Quick Silver"),
_("Hampshire"),
_("Keep Off The Grass!"),
_("Slugfest"),
_("Magic"),
_("Six heroes with large armies prepare to slug it out for total domination!"),
_("Bloodreign"),
_("Atlantium"),
_("Quick Silver"),
_("Woodhaven"),
_("Sandcaster"),
_("Forder Oaks"),
_("Spell Casters"),
_("The four spell casters face off with substantial starting armies. Can the crusaders keep the peace?"),
_("Baywatch"),
_("Wildabar"),
_("Nightshadow"),
_("Sandcaster"),
_("Burlock"),
_("Alamar"),
_("Surf and Turf"),
_("More water than land, you'll still spend lots of time on foot as you search a literal horde of islands."),
_("Whiteshield"),
_("Bloodreign"),
_("Dragontooth"),
_("Middle Gate"),
_("Tundara"),
_("Atlantium"),
_("Baywatch"),
_("Wildabar"),
_("Fountainhead"),
_("Winterkill"),
_("Sandcaster"),
_("Lakeside"),
_("Olympus"),
_("Brindamoor"),
_("Burlock"),
_("Xabran"),
_("Dragadune"),
_("Alamar"),
_("Kalindra"),
_("Blackfang"),
_("Algary"),
_("Sorpigal"),
_("New Dawn"),
_("Erliquin"),
_("Avone"),
_("Teleporters"),
_("For a total of 400,000 gold your opponents will become \"loyal\" subjects, otherwise... let them eat cake!"),
_("Quick Silver"),
_("Burlock"),
_("Blackwind"),
_("Blacksford"),
_("Troy"),
_("Timberhill"),
_("Vulcania"),
_("Hilltop"),
_("Weed Patch"),
_("Whiteshield"),
_("Corackston"),
_("Antioch"),
_("Yorksford"),
_("Hillstone"),
_("You find a gleaming gold medalion buried in the  snow.  As you move to put it on it changes to the Fizbin of Misfortune."),
_("You find a beautiful helm buried in the lava.  As you move to put it on your head it turns into the Hideous mask and now you realize that no creature will join you."),
_("A large contingent of the king's guard approaches you.  \"Ahh, we have finally caught up to you.  The king requires tribute from all of his vassals and you have been negligent far too long.\""),
_("Terra Firma"),
_("A wild magic has allowed a bridge to form between two lands...  Your one hope is to capture castle \"Black Fang\"."),
_("Black Fang"),
_("Vertigo"),
_("After many years of peace, you discover that your sworn enemy from across the sea has chosen to invade your homeland by raising up the ocean floor to bridge the distance! You must not let them gain a foothold on this continent, in fact, your King has ordered you to establish a foothold on theirs!  To make matters worse, two of your OWN towns have thrown in their lots with the enemy..."),
_("It is rumored that a bridge of land used to exist between the two continents, but that a wild magic caused it to sink into the sea, taking with it all those who used to inhabit it.  To try to raise this bridge is to invite a curse upon the world!  The spirits of the dead will haunt us all!"),
_("Sorpigal"),
_("Blacksford"),
_("Erliquin"),
_("Avone"),
_("Big Oak"),
_("Hampshire"),
_("Chandler"),
_("We found a weakness my lord. Capture castle Black Fang and victory is ours."),
_("Your king has sent supplies to aid the war effort."),
_("Terrain Wars"),
_("This rugged land will have rivals fighting the terrain as well as each other."),
_("Dragontooth"),
_("Greywind"),
_("Middle Gate"),
_("Tundara"),
_("Vulcania"),
_("Sansobar"),
_("Woodstock"),
_("Grrr, Blazzer, Grrupt. Be gone with you!"),
_("Someone has stolen 100 wood and 77 ore from you. Ah, that's nothing. Let's keep going."),
_("Baywatch"),
_("Fountainhead"),
_("Vertigo"),
_("Winterkill"),
_("Sandcaster"),
_("Lakeside"),
_("Olympus"),
_("Brindamoor"),
_("Burlock"),
_("Grim"),
_("Go north to find the lost gold-mine."),
_("Lost Gold- Mine"),
_("Password found by Crystals to the South."),
_("The Medusas have the password and they can be found just to the west."),
_("I see you, you see me."),
_("The Back Door"),
_("Many guardians stand between you and your enemies, but anybody can sneak through the back door!"),
_("Erliquin"),
_("Weed Patch"),
_("Roc Haven"),
_("New Dawn"),
_("Atlantium"),
_("The Clearing"),
_("Find the Ultimate Artifact and be proclaimed King, or smash the opposition and take control."),
_("Dragadune"),
_("Alamar"),
_("Kalindra"),
_("Blackfang"),
_("Big Oak"),
_("The Other Side"),
_("A resource rich valley keeps the Wizard and the Necromancer apart. Your opponent's army will arrive in 3 months so hurry."),
_("Vertigo"),
_("Winterkill"),
_("Time is running out! The enemy's reinforcements are almost here."),
_("Hurry up! Few days are left before the enemy's army arrives."),
_("Undead Armies"),
_("A plague of undead is upon us. Who will unite the living against the dead?"),
_("Hillstone"),
_("Vertigo"),
_("Olympus"),
_("Dragadune"),
_("Basenji"),
_("Algary"),
_("Sorpigal"),
_("Erliquin"),
_("Avone"),
_("Big Oak"),
_("Unholy Alliance"),
_("A Knight and Necromancer team up against the Barbarian and Sorceress. (Blue and Green vs Red and Yellow)"),
_("Whiteshield"),
_("Blackwind"),
_("Vulcania"),
_("Sansobar"),
_("Atlantium"),
_("Baywatch"),
_("Wildabar"),
_("Fountainhead"),
_("Valley of Death"),
_("You have six months to destroy the Necromancer Stronghold in the heart of the valley."),
_("Vulcania"),
_("Sansobar"),
_("Atlantium"),
_("Wildabar"),
_("Fountainhead"),
_("Winterkill"),
_("Nightshadow"),
_("Sandcaster"),
_("The edge of the world is your edge.  But prepare to be prepared."),
_("Brindamoor"),
_("Vikings!"),
_("Barbarians from the north threaten all civilization. Can you repel the hordes?"),
_("Erliquin"),
_("Big Oak"),
_("Hampshire"),
_("Weddington"),
_("Lombard"),
_("Timberhill"),
_("Forder Oaks"),
_("Meramec"),
_("Quick Silver"),
_("Westmoor"),
_("Willow"),
_("Corackston"),
_("Blackridge"),
_("Pinehurst"),
_("Warrior Knight"),
_("Pick one of four Knights in this large and inhospitable land."),
_("Blackburn"),
_("Lankershire"),
_("Lombard"),
_("Timberhill"),
_("Fenton"),
_("Troy"),
_("Pinehurst"),
_("Woodhaven"),
_("Hillstone"),
_("Lost Island."),
_("Whiteshield"),
_("Bloodreign"),
_("Dragontooth"),
_("Greywind"),
_("Blackwind"),
_("Portsmith"),
_("Middle Gate"),
_("Tundara"),
_("Wastelands"),
_("The Barbarian's lands are being invaded. Are you strong enough to resist the invasion?"),
_("Xabran"),
_("Dragadune"),
_("Erliquin"),
_("Avone"),
_("Your subjects contribute to your war effort!"),
_("South Mill"),
_("Weed Patch"),
_("Roc Haven"),
_("Avalon"),
_("Detour! Troll bridge ahead!"),
_("Roscomon"),
_("Danger! Troll bridge ahead!"),
_("My leige, our scouts report three other lords are attacking from the south. They work in conjuction with each other to eliminate us! We must keep this castle and remove the threat of the enemy. We wish you luck!"),
_("Who am I?"),
_("A stranded Wizard with only a small force must conquer an entire continent of hostile forces."),
_("Yorksford"),
_("Antioch"),
_("Lakeside"),
_("Whittingham"),
_("Erliquin"),
_("Sandcaster"),
_("New Dawn"),
_("Westmoor"),
_("Woodhaven"),
_("Dragontooth"),
_("Greywind"),
_("Portsmith"),
_("Who am I?...  Where am I?...  Oh no! My Ship!  Well it's consigned to the ghosts of my dead crew now, at least I still have my lucky rabbits foot."),
_("Scouts have reported a town to the North.  They have also heard some disturbing news.  Their seems to be a war raging in this area."),
_("Go Home!"),
_("Middle Gate"),
_("Welcome back general.  Have you finished the conquest of the northern lands?  What? you still have not finished your mission!  Get back there and teach those rebels a lesson!"),
_("Who am I?"),
_("Baywatch"),
_("Wildabar"),
_("The troops have sworn their allegiance, but should lose a battle they will lose faith and our cause will be lost."),
_("Winterlands"),
_("A large map with lots of resources and treasure. Exploration and victory will require many heroes."),
_("Hillstone"),
_("Icy lands ahead."),
_("Bridge out!"),
_("Rest stop."),
_("Fenton"),
_("Westmoor"),
_("Willow"),
_("Corackston"),
_("Pinehurst"),
_("Woodhaven"),
_("Dragontooth"),
_("Greywind"),
_("Tundara"),
_("Sansobar"),
_("Baywatch"),
_("Witch Hunt"),
_("You must search the world for your mortal enemy, Wilgatus.  Can you find him before its too late?"),
_("Olympus"),
_("Brindamoor"),
_("Dragadune"),
_("New Dawn"),
_("Avone"),
_("Big Oak"),
_("Hampshire"),
_("Chandler"),
_("South Mill"),
_("Westfork"),
_("Hilltop"),
_("Land teleporters will get you to your destination sooner."),
_("Beware -- Entering Hyrda Country"),
_("Now leaving Swamplands of the Eternial"),
_("Boats Sold Here            Inquire Within"),
_("Entering Praires of the Middlelands"),
_("Right thinking - he who takes the riskes deserves the rewards."),
_("As you lay down to nap after a long battle, you notice a lucky four-leaf clover."),
_("Beware of traps ahead."),
_("I, Wilgatus, besiege you - do not fight me for I am all powerful and will destroy you if you persue me.  I will demonstrate my power."),
_("Time for a refreshing drink."),
_("You stumple across three small rocks piled on top of each other and decide to dig undernear them.  There you find an old weather-beaten bag of gems."),
_("The Valley of Magic holds many surprises.  You discover an old pair of boots sticking out of the sand."),
_("Beware for whom the bell trolls."),
_("To pass you must pay troll."),
_("POSION - DO NOT DRINK"),
_("We told you not to drink!"),
_("You're getting warmer."),
_("You're getting colder."),
_("Danger - Turn Back Now"),
_("The Valley of Tresures"),
_("The King has declared you his hier apparent and champion. You must seek out and destroy your common enemy, Wilgatus and his Castle, Mirkosov, the source of his power."),
_("Sherman"),
_("Mirkosov"),
_("You stumble upon an old man who proclaims you Lord of the Realm, hands you his boots and wonders into the mountains mumbling something about being late for an important date."),
_("Viper's Nest"),
_("The key to success is rubbing enough lamps."),
_("Entering the Valley of Magic"),
_("Pig's Eye"),
_("Blacksford"),
_("At the base of the mountain you see something that glitters.   You discover an ancient pile of offerings to the gods."),
_("Lankershire"),
_("Lombard"),
_("Wilgatus"),
};

#endif
