# makefile
#

TARGET = fheroes2.exe
LIBS = `sdl-config --libs`
CFLAGS = -O2 -Wall -fomit-frame-pointer `sdl-config --cflags`

CC = g++

all: $(TARGET)
	strip $(TARGET)

fheroes2.exe: $(patsubst %.cpp, %.o, $(wildcard *.cpp))
	$(CC) $^ -o $@ $(LIBS)

%.o: %.cpp
	$(CC) -c -MD $< $(CFLAGS)

include $(wildcard *.d)

.PHONY: clean

clean:
	rm *.o
	rm *.d
	rm $(TARGET)
