# makefile
# project: Free Heroes2
#

TARGET = fheroes2.exe
LIBS = -lSDLmain -lSDL
CFLAGS = -O2 -I /cygdrive/c/cygwin/usr/include
CC = gcc

all: $(TARGET)
	strip $(TARGET)

fheroes2.exe: $(patsubst %.c, %.o, $(wildcard *.c))
	$(CC) $^ -o $@ $(LIBS)

%.o: %.c
	$(CC) -c -MD $< $(CFLAGS)

include $(wildcard *.d)

.PHONY: clean

clean:
	rm *.o
	rm *.d
	rm $(TARGET)
