ifndef WITHOUT_MIXER
LIBS := $(LIBS) -lSDL -lmad -lvorbisfile -lvorbis -logg
endif

ifndef WITHOUT_UNICODE
LIBS := $(LIBS) -lintl -lfreetype
endif

AR := arm-mingw32ce-ar
CXX := arm-mingw32ce-g++
CFLAGS := $(CFLAGS) -Os -static
LIBS := -Wl,-Bstatic $(LIBS) -lmmtimer
